config/routes.rb
Rails.application.routes.draw do
  get 'event/new'
  post '/event/create', to: 'event#create'
  get 'static_pages/index'
  get 'static_pages/secret'
  devise_for :users
  root to: "static_pages#index"
  get 'event/view'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :events
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_controller.rb
class EventController < ApplicationController
  def new

  end
  def create
    puts "$" * 60
    puts "Voici le message de l'URL :"
    puts  params
    puts "$" * 60
    author = current_user
    @event= Event.create(user: author,title:params["title"],content:params["content"],location:params["location"],price:params["price"] )
    puts @event
    puts author 
    puts params["title"]
    puts params["content"]
    puts params["location"]
    puts params["price"]
    if @event.save
       puts "saved"
       redirect_to"/event/view"
    else
      puts "non valide"
      redirect_to"/event/new"
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  def index
  end

  def secret
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/event/new.html.erb
<form action="/event/create" method="POST">
<div class="mb-3 d-flex justify-content-center">
<p>Titre
  <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >
  <input type="text" name="title" required="required"></p>
  </div>
  <div class="mb-3 d-flex justify-content-center">
  <p>date:
 <input type="text" name="date" required="required">
  durée (en minutes)
  <input type="text" name="duration" required="required"></p>
  </div>
  <p class="d-flex justify-content-center" >Prix
  <input type="text" name="price" required="required">€  lieu :
  <input type="text" name="location" required="required"></p>
  <p class="d-flex justify-content-center" >Description</p>
  <p class="d-flex justify-content-center">
  <textarea id="content" name="content" rows="10" cols="70"></textarea>
  </p>
  <p class="d-flex justify-content-center">
  <input type="submit" value="Valider">
  </p>
</form>

app/views/event/view.html.erb
<h1>Accueil</h1>
<h2>Bienvenue sur The Gossip Project</h2>
<body>
  <h5>LIste des gossips :</h5>  
  <div class="container">
    <div class="row row-cols-4" style="color: black">
      <% Event.all.each do |event| %>
      <% author = event.user %>
      <% link_gossip = "/gossip/"+event.id.to_s%>
      <% #link_author = "/user/"+author.id.to_s%>
      <div class ="col">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
          <h5 class="card-title"><%= link_to "#{event.title}",link_gossip%></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%=event.updated_at%></h6>
          <h6 class="card-subtitle mb-2 text-muted"><%=event.location%></h6>
          <h6 class="card-subtitle mb-2 text-muted"><%=event.price%>€</h6>
          <p class="card-text"><%=event.content%></p>
        </div>
      </div>
      </div>
  <% end %>
  </div> 
 </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapptest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href="/users/sign_in">Callendapp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    <li class="nav-item">
    <a class="nav-link d-flex flex-row-reverse" href="/event/view">Evenements</a>
  </li>
      <li class="nav-item active">
        <a class="nav-link" href="/event/new">Créer un event</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/static_pages/secret">Mon profil</a>
      </li>
    </ul>
  </div>
</nav>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>